### ISSUE TITLE
Get red expection

### ISSUE THREAD

**Issue by pi-dash** [74Labs/node-red-contrib-google#4]
JSON credentials is well set,
apis, operations and scopes are well listed in select box of node config

When try to launch api call (ex gmail:v1 / labels.list) , i got red exception

datetime - [red] Uncaught Exception:
datetime - TypeError: Cannot read property 'list' of undefined
at /usr/lib/node_modules/node-red-contrib-google/google.js:143:42
at Array.forEach (native)
at /usr/lib/node_modules/node-red-contrib-google/google.js:142:23

Similar exception regardless the operation choosen fron listbox.

edit : all googleapis dependencies are well installed during npm install node-red-contrib-google.
other node client (not red), work well with the same google-api-nodejs-client

edit: sorry, i forgot the best practice in that situation. 1) to say hello, 2) to thanks you for the job accomplished.

**Comment by TomStanczyk** [comment]
Fixed at 0.2.0. Please update and check.

**Comment by pi-dash** [comment]
Hi,

Thanks for you quick feedback.

This version seems to fix the prefix on operation.
After update, i was able to perform google api request.

However, i'm still receiving error (but no more red exception now)
on some GG apis, red log show "error] [google:_my_node_nodered_name_] Error: Bad Request"
then some return "[error] [google:_my_node_nodered_name_] Error: Insufficient Permission"

the second is quite easy to troubleshoot as due to service account given roles (and eventual delegation).
the first less. and errors appear especially on gmail:v1, that it seems, following google api client doc,  require specific settings/authentication (on google api console / gmail client srv).

Before to go further in node-red with intensive use of your node, my first purpose is to use your node only to regularly check unread mail then display and notifiy in dashboard on red.

Can you confirm us that gmail works here in node-red (i confirm it works in simple node with client_secret.json, not service account), and eventually drive us on how to set google service account key (role/perm) and your node (config on google-conn and input param payload)

Thanks

**Comment by TomStanczyk** [comment]
Hello pi-dash,

Can you specify operations which gives you "bad request" and "insufficient permissions"?

**Comment by pi-dash** [comment]
Hello Tom,

1.
One in success : drive:v3 > files.list
```
msg.payload : Object
object
  kind: "drive#fileList"
  incompleteSearch: false
  files: array[1]
    0: object
      kind: "drive#file"
      id: "xxxxxxxxxxxxxx"
      name: "Getting started"
      mimeType: "application/pdf"
```
But it seems access to service account drive account (cause Getting started.pdf), I think that drive API also supports behalf of access in order to access to drive repo to regular Google User (in my own google drive account, I have about dozens of files)

2. 
One in bad request : gmail:v1 > users.labels.list (i almost try all operators) and it always returns
```
msg : error
"Error: Bad Request"
```
I think is due to json key used (google gmail API client expects to use client_secret.json not service account one)

3.
Then, since i have fixed service account permissions, i don't receive "Insufficient Permission"
but it was on calendar:v3 > calendarList.list (and any other too)
now it works, but i think (like for drive), it also access/display the calendar of my service account only
```
msg.payload : Object
object
  kind: "calendar#calendarList"
  etag: ""p338b5ck4j7nta0g""
  nextSyncToken: "XXXXXXXXXXXXXX"
  items: array[0]
```

4.
Note : to perform short test, each time I select API/Operation, I always copy/paste proposed scopes into google_conn config

My thinks are:
- Some  Google APIs are free/public, quite easy to use and have good/correct responses
- Some  Google APIs are relevant to Google Cloud, which require specific settings on service account, and return only data relevant to that account (or at least your cloud account apps)
- Some  Google APIs require access on behalf of another user (I especially think to regular google accounts, not google apps accounts), which require a normal user authorization consent (thru Oauth)

On my node test, with direct use of google-api-nodejs-client and quickstart
found here https://developers.google.com/gmail/api/quickstart/nodejs
this node app uses client_secret.json, not service_account.json (it returns errors if second is used)
In good kinematic, we have
- It checks our client_secret.json file
- It generate an authorization link
- We copy/paste this link into our browser
- It generate an authorization token after OAuth consent
- We copy/paste this token into the prompt proposed by app node
- Node app store consent (so later uses don't prompt authorization link at all)
- It access our gmail account (the one of selected account during consent) and return users.labels.list

It also seems that google gmail doesn't allow to delegate (grant access feature) an access to the mail address given to service account, which looks like:
your_service_account@your_cloud_app_ID.iam.gserviceaccount.com
Google considers that it's not a valid email for that purpose

For gmail, I can use the regular IMAP node of node-red, but it generates an heavy network traffic as it requests mail by mail. So it's not suitable just to retrieve the amount of unread mail (i don't need the topic nor body of each and we cannot perform query search). In regular Google Gmail API, it just returns the id of each mail and a json interger key for counter (which I expect to use here) and it supports query search (eg returns mail only for specific label, etc.)

Regards

**Comment by TomStanczyk** [comment]
Hi, 

Thanks for a such comprehensive explanation.

ad 1,3:
For Drive and Calendar you have to give service account access to your account resources. It can be done like for regular users. Just share your calendar and/or drive files/folders with service account (use service account mail).

> It also seems that google gmail doesn't allow to delegate (grant access feature) an access to the mail address given to service account

You are absolutely right.

Drive and Calendar are much simpler because of possiblity to grant service account access to your resources. That possibility is missing in regular Gmail, only OAuth is supported.

The only way to give service account access to mail box is GSuite (corporate like Google services). There is switch in service account options for that scenario.

I'm affraid that IMAP is solution/workaround for you.

Best regards

**Comment by pi-dash** [comment]
Hi,

Thanks for your fast answer.

IMAP could be ok for few unread mails. If you have hundreds nor thousands of unreaded, it can take several minutes to load all mails (just for a counter :) ).
As I still need to access regular Google accounts, I have to play with OAuth, so I will probably try to wrap something similar to above quickstart.js as a new node for node-red.

My approach is to use stored consent after token prompt:
- Deploy your node in node-red flow and get its ID (display a warning marker as not well set yet)
- Init OAuth consent by CLI (client_secret.json path + node ID + link generation + token prompt)
- node app stores consent for this node-red node ID
- Open node-red node config, click on button [Check consent] (remove warning marker)
- Use the node in our flow

Input : probably just a trigger to start API call as a PoC (enhanced later with API input payload,operators, etc.)
Output : output of API

Study:
- a way to use node-red-dashboard interaction to replace CLI consent later.
- to extend this node to all APIs that request OAuth and client_secret.json for behalf of access (not only gmail) (but I'm pretty sure that only gmail is specific)

Regards,
